defaults:
  permissions:
    - ecm/staff/backend/engine
    - ecm/staff/business_unit/index
    - ecm/staff/business_unit/show
    - ecm/staff/business_unit/new
    - ecm/staff/business_unit/create
    - ecm/staff/business_unit/edit
    - ecm/staff/business_unit/update
    - ecm/staff/business_unit/destroy
    - ecm/staff/organisation/index
    - ecm/staff/organisation/show
    - ecm/staff/organisation/new
    - ecm/staff/organisation/create
    - ecm/staff/organisation/edit
    - ecm/staff/organisation/update
    - ecm/staff/organisation/destroy
    - ecm/staff/person/index
    - ecm/staff/person/show
    - ecm/staff/person/new
    - ecm/staff/person/create
    - ecm/staff/person/edit
    - ecm/staff/person/update
    - ecm/staff/person/destroy
    - ecm/staff/position/index
    - ecm/staff/position/show
    - ecm/staff/position/new
    - ecm/staff/position/create
    - ecm/staff/position/edit
    - ecm/staff/position/update
    - ecm/staff/position/destroy
  roles:
    ecm/staff/administrator:
      - ecm/staff/backend/engine
      - ecm/staff/business_unit/index
      - ecm/staff/business_unit/show
      - ecm/staff/business_unit/new
      - ecm/staff/business_unit/create
      - ecm/staff/business_unit/edit
      - ecm/staff/business_unit/update
      - ecm/staff/business_unit/destroy
      - ecm/staff/organisation/index
      - ecm/staff/organisation/show
      - ecm/staff/organisation/new
      - ecm/staff/organisation/create
      - ecm/staff/organisation/edit
      - ecm/staff/organisation/update
      - ecm/staff/organisation/destroy
      - ecm/staff/person/index
      - ecm/staff/person/show
      - ecm/staff/person/new
      - ecm/staff/person/create
      - ecm/staff/person/edit
      - ecm/staff/person/update
      - ecm/staff/person/destroy
      - ecm/staff/position/index
      - ecm/staff/position/show
      - ecm/staff/position/new
      - ecm/staff/position/create
      - ecm/staff/position/edit
      - ecm/staff/position/update
      - ecm/staff/position/destroy
    ecm/staff/reviewer:
      - ecm/staff/backend/engine
      - ecm/staff/business_unit/index
      - ecm/staff/business_unit/show
      - ecm/staff/organisation/index
      - ecm/staff/organisation/show
      - ecm/staff/person/index
      - ecm/staff/person/show
      - ecm/staff/position/index
      - ecm/staff/position/show
